/* Krueka Crea · estudio creativo del Club · 20260828a */
(function(){
'use strict';
if(typeof Club==='undefined') return;

var VERSION='20260828a';
var css=document.createElement('link');
css.rel='stylesheet';
css.href=(window.KRUEKA_BASE||'')+'club/club-crea.css?v='+VERSION;
css.dataset.kruekaCrea='1';
document.head.appendChild(css);

var TIPOS={
  game:{nombre:'Juego',icono:'🎮',color:'#6959c9'},
  web:{nombre:'Página web',icono:'🌐',color:'#087b82'},
  design:{nombre:'Diseño',icono:'🎨',color:'#d05f75'}
};
var WEB_TEMPLATES={
  neon:{nombre:'Perfil neón',icono:'⚡',html:'<main class="perfil">\n  <div class="avatar">🚀</div>\n  <p class="kicker">CREADOR DIGITAL</p>\n  <h1>Hola, soy Alex</h1>\n  <p>Me gusta crear juegos, dibujar personajes y aprender tecnología.</p>\n  <div class="badges"><span>🎮 Juegos</span><span>🎨 Diseño</span><span>💻 Código</span></div>\n  <button id="saludo">Tocá aquí</button>\n  <p id="mensaje"></p>\n</main>',css:'body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at top,#233873,#080b1c);font-family:system-ui;color:#fff}.perfil{width:min(520px,86vw);padding:42px;text-align:center;border:1px solid #4fffe1;border-radius:28px;background:#0d1736cc;box-shadow:0 0 45px #4fffe133}.avatar{font-size:72px}.kicker{letter-spacing:.18em;color:#4fffe1;font-weight:800}h1{font-size:clamp(34px,8vw,62px);margin:8px 0}p{line-height:1.6}.badges{display:flex;justify-content:center;gap:8px;flex-wrap:wrap}.badges span{padding:8px 12px;border-radius:999px;background:#ffffff14}button{margin-top:24px;padding:12px 20px;border:0;border-radius:12px;background:#ffcc4d;font-weight:800;cursor:pointer}',js:"document.querySelector('#saludo').addEventListener('click',function(){document.querySelector('#mensaje').textContent='¡Gracias por visitar mi página! ✨'})"},
  aventura:{nombre:'Mi aventura',icono:'🗺️',html:'<main>\n  <p class="capitulo">CAPÍTULO 1</p>\n  <h1>El bosque de los códigos</h1>\n  <p id="historia">Una puerta brillante apareció entre los árboles.</p>\n  <div class="acciones"><button data-op="entrar">Entrar</button><button data-op="volver">Volver</button></div>\n</main>',css:'body{margin:0;min-height:100vh;display:grid;place-items:center;background:linear-gradient(#173d2c,#081a18);font-family:Georgia,serif;color:#f6f0d7}main{width:min(620px,84vw);padding:48px;border:2px solid #d6b85e;border-radius:18px;background:#102a25;box-shadow:0 24px 70px #0008}.capitulo{font:700 12px system-ui;letter-spacing:.2em;color:#e6c967}h1{font-size:clamp(38px,8vw,70px);line-height:1;margin:10px 0 22px}p{font-size:19px;line-height:1.7}.acciones{display:flex;gap:12px;margin-top:28px}button{padding:12px 20px;border:1px solid #e6c967;border-radius:10px;background:transparent;color:#f6f0d7;font-weight:700;cursor:pointer}button:hover{background:#e6c967;color:#102a25}',js:"document.querySelectorAll('button').forEach(function(b){b.addEventListener('click',function(){var entrar=b.dataset.op==='entrar';document.querySelector('#historia').textContent=entrar?'Entraste. Un zorro te entrega el primer bloque mágico. 🦊':'Volvés al campamento para preparar mejor tu mochila. 🎒'})})"},
  mascota:{nombre:'Mi mascota',icono:'🐾',html:'<main>\n  <div id="mascota" aria-label="Mascota">🐶</div>\n  <h1>Toby</h1>\n  <p>Le encantan las aventuras y las galletitas.</p>\n  <button id="jugar">Jugar</button>\n</main>',css:'body{margin:0;min-height:100vh;display:grid;place-items:center;background:#ffe9b8;font-family:system-ui;color:#24313a}main{text-align:center;width:min(420px,82vw);padding:36px;background:#fff;border:4px solid #24313a;border-radius:30px;box-shadow:10px 10px 0 #ff826e}#mascota{font-size:100px;transition:transform .2s}h1{font-size:46px;margin:4px 0}p{font-size:18px}button{padding:13px 24px;border:0;border-radius:14px;background:#24313a;color:#fff;font-weight:800;font-size:17px;cursor:pointer}.saltando{transform:translateY(-24px) rotate(-8deg)}',js:"document.querySelector('#jugar').addEventListener('click',function(){var m=document.querySelector('#mascota');m.classList.add('saltando');setTimeout(function(){m.classList.remove('saltando')},350)})"}
};
function copia(v){return JSON.parse(JSON.stringify(v));}
function ahora(){return new Date().toISOString();}
function localId(){return 'local-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
function descarga(nombre,texto,tipo){var b=new Blob([texto],{type:tipo||'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=nombre;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000);}

var KruekaCrea={
  current:null,projects:[],saveTimer:null,previewTimer:null,webTab:'html',busy:false,
  sid:function(){return Club.sid?Club.sid():(Club.alumno&&(Club.alumno.student_id||Club.alumno.id));},
  device:function(){return typeof deviceId==='function'?deviceId():null;},
  localKey:function(){return 'krueka_crea_projects_'+(this.sid()||'visitante');},
  localProjects:function(){try{var x=JSON.parse(localStorage.getItem(this.localKey())||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}},
  writeLocal:function(list){try{localStorage.setItem(this.localKey(),JSON.stringify(list.slice(0,30)))}catch(e){}},
  saveLocal:function(project){var list=this.localProjects(),i=list.findIndex(function(x){return x.id===project.id}),clean=copia(project);if(i>=0)list.splice(i,1);list.unshift(clean);this.writeLocal(list);},
  removeLocal:function(id){this.writeLocal(this.localProjects().filter(function(x){return x.id!==id}))},
  status:function(text,kind){var el=document.getElementById('crea-save-status');if(!el)return;el.textContent=text;el.dataset.kind=kind||'';},
  baseContent:function(type){if(type==='web')return copia(WEB_TEMPLATES.neon);if(type==='game')return {fondo1:'#173f7a',fondo2:'#6457ba',jugador:'🚀',premio:'⭐',sonido:true,reglas:[{evento:'flecha',accion:'mover',valor:22},{evento:'tocar',accion:'sumar',valor:1},{evento:'tocar',accion:'teletransportar',valor:0},{evento:'puntos',accion:'ganar',valor:5}]};return {size:16,pixels:Array(256).fill(null),color:'#6959c9',tool:'paint',brush:1,grid:true};},
  project:function(type){return {id:localId(),type:type,title:type==='game'?'Mi primer juego':type==='web'?'Mi página web':'Mi personaje',status:'draft',version:1,content:this.baseContent(type),updated_at:ahora(),local_only:true};},
  rpc:async function(name,args){var r=await db.rpc(name,args);if(r.error)throw r.error;return r.data;},
  list:async function(){var local=this.localProjects(),remote=[];try{var data=await this.rpc('club_crea_listar',{p_student:this.sid(),p_device:this.device()});remote=Array.isArray(data)?data:[]}catch(e){}var map={};remote.concat(local).forEach(function(p){if(p&&p.id&&!map[p.id])map[p.id]=p});this.projects=Object.keys(map).map(function(k){return map[k]}).sort(function(a,b){return String(b.updated_at||'').localeCompare(String(a.updated_at||''))});return this.projects;},
  insertEntry:function(){if(!Club.alumno||document.getElementById('krueka-crea-entry'))return;var hero=document.querySelector('#club-box .club-dashboard-hero');if(!hero)return;var local=this.localProjects().length,card=document.createElement('section');card.id='krueka-crea-entry';card.className='crea-entry';card.innerHTML='<div class="crea-entry-mark" aria-hidden="true">✦</div><div><span class="club-kicker">NUEVO · ESTUDIO CREATIVO</span><h2>Creá a tu manera</h2><p>Programá juegos y páginas, dibujá personajes y guardá todo en tu propio taller.</p><div class="crea-entry-tags"><span>🎮 Juegos</span><span>🌐 Web</span><span>🎨 Diseño</span>'+(local?'<span>💾 '+local+' proyecto'+(local===1?'':'s')+'</span>':'')+'</div></div><button class="club-primary" type="button" onclick="KruekaCrea.abrir()">Abrir Krueka Crea →</button>';hero.insertAdjacentElement('afterend',card);},
  async abrir(){this.stopGame&&this.stopGame();Club.pinta(Club.cabecera('Krueka Crea','Club.volverMapa()')+'<div class="crea-loading"><i></i><p>Abriendo tu taller…</p></div>');await this.list();this.home();},
  home:function(){var self=this,recent=this.projects.slice(0,4),cards=recent.length?recent.map(function(p){return self.card(p)}).join(''):'<div class="crea-empty"><span>✨</span><h3>Tu taller está listo</h3><p>Elegí qué querés crear y tu primer proyecto aparecerá acá.</p></div>';Club.pinta(Club.cabecera('Krueka Crea','Club.volverMapa()')+'<main class="crea-home"><section class="crea-hero"><div><span class="club-kicker">TU ESTUDIO · TODO EN UN SOLO LUGAR</span><h1>¿Qué querés crear hoy?</h1><p>Elegí una idea, personalizala y probala. Krueka guarda cada avance para que puedas continuar después.</p></div><div class="crea-hero-orbit" aria-hidden="true"><b>✦</b><i>🎮</i><i>🌐</i><i>🎨</i></div></section><section class="crea-start-grid"><button class="crea-start game" onclick="KruekaCrea.nuevo(\'game\')"><span>🎮</span><b>Crear un juego</b><small>Programá reglas, puntos y personajes.</small><em>Ideal para empezar</em></button><button class="crea-start web" onclick="KruekaCrea.nuevo(\'web\')"><span>🌐</span><b>Crear una página</b><small>HTML, colores, botones y movimiento.</small><em>Vista en vivo</em></button><button class="crea-start design" onclick="KruekaCrea.nuevo(\'design\')"><span>🎨</span><b>Diseñar personaje</b><small>Dibujá píxel por píxel y usalo en juegos.</small><em>Mouse, táctil o teclado</em></button></section><section class="crea-recent"><div class="crea-section-title"><div><span class="club-kicker">MIS PROYECTOS</span><h2>Continuá donde quedaste</h2></div><button class="crea-link" onclick="KruekaCrea.verProyectos()">Ver todos →</button></div><div class="crea-project-grid">'+cards+'</div></section><section class="crea-safe"><span>🛡️</span><div><b>Un lugar seguro para experimentar</b><p>Los proyectos son privados. El código se prueba aislado y nada se publica sin revisión de dirección.</p></div></section></main>');},
  card:function(p){var t=TIPOS[p.type]||TIPOS.web,status=p.status==='review'?'En revisión':p.status==='published'?'Aprobado':'Borrador';return '<article class="crea-project" style="--pc:'+t.color+'"><button class="crea-project-open" onclick="KruekaCrea.abrirProyecto(\''+esc(p.id)+'\')"><span>'+t.icono+'</span><div><small>'+esc(t.nombre)+' · '+esc(status)+'</small><b>'+esc(p.title||'Sin título')+'</b><em>'+esc(this.relative(p.updated_at))+'</em></div></button><div class="crea-project-actions"><button onclick="KruekaCrea.duplicar(\''+esc(p.id)+'\')">Duplicar</button><button onclick="KruekaCrea.archivar(\''+esc(p.id)+'\')">Archivar</button></div></article>';},
  relative:function(iso){if(!iso)return'Sin guardar';var d=Math.max(0,Date.now()-new Date(iso).getTime()),m=Math.floor(d/60000);return m<1?'Guardado ahora':m<60?'Hace '+m+' min':m<1440?'Hace '+Math.floor(m/60)+' h':'Hace '+Math.floor(m/1440)+' día(s)';},
  nuevo:function(type){if(!TIPOS[type])return;this.current=this.project(type);this.saveLocal(this.current);this.openEditor();},
  async abrirProyecto(id){var p=this.projects.find(function(x){return x.id===id})||this.localProjects().find(function(x){return x.id===id});if(!p)return this.abrir();if(!p.content&&!String(id).startsWith('local-')){try{p=await this.rpc('club_crea_cargar',{p_student:this.sid(),p_device:this.device(),p_project:id})}catch(e){alert('No pudimos abrir ese proyecto.');return}}this.current=copia(p);this.openEditor();},
  openEditor:function(){this.stopGame&&this.stopGame();if(!this.current)return this.abrir();if(this.current.type==='web')this.renderWeb();else if(this.current.type==='game'&&this.renderGame)this.renderGame();else if(this.current.type==='design'&&this.renderDesign)this.renderDesign();else this.abrir();},
  editorTop:function(label,extra){var p=this.current;return '<div class="crea-editor-top"><button class="crea-icon" onclick="KruekaCrea.abrir()" aria-label="Volver a mis proyectos">←</button><div class="crea-editor-name"><small>'+esc(label)+'</small><input id="crea-title" maxlength="80" value="'+esc(p.title||'')+'" aria-label="Nombre del proyecto" oninput="KruekaCrea.renombrar(this.value)"></div><div id="crea-save-status" class="crea-save-status" aria-live="polite">Guardado en este equipo</div><div class="crea-editor-actions">'+(extra||'')+'<button class="club-primary" onclick="KruekaCrea.guardar(true)">Guardar</button></div></div>';},
  renombrar:function(v){if(!this.current)return;this.current.title=String(v||'').slice(0,80);this.programarGuardado();},
  programarGuardado:function(){if(!this.current)return;this.current.updated_at=ahora();this.saveLocal(this.current);this.status('Borrador guardado','local');clearTimeout(this.saveTimer);var self=this;this.saveTimer=setTimeout(function(){self.guardar(false)},900);},
  async guardar(forzado){if(!this.current||this.busy)return;var p=this.current,oldId=p.id;this.saveLocal(p);this.status('Guardando…','busy');this.busy=true;try{var data=await this.rpc('club_crea_guardar',{p_student:this.sid(),p_device:this.device(),p_project:String(p.id).startsWith('local-')?null:p.id,p_type:p.type,p_title:(p.title||'Proyecto sin título').slice(0,80),p_content:p.content});if(data&&data.id){p.id=data.id;p.local_only=false;p.version=data.version||p.version;p.status=data.status||p.status;p.updated_at=data.updated_at||ahora();if(oldId!==p.id)this.removeLocal(oldId);this.current=p;this.saveLocal(p)}this.status('Guardado en Krueka ✓','ok')}catch(e){this.status(forzado?'Guardado en este equipo · sin conexión':'Borrador local','local')}this.busy=false;},
  async verProyectos(){await this.list();var self=this,cards=this.projects.length?this.projects.map(function(p){return self.card(p)}).join(''):'<div class="crea-empty"><span>✨</span><h3>Todavía no hay proyectos</h3><p>Creá tu primer juego, página o personaje.</p></div>';Club.pinta(Club.cabecera('Mis proyectos','KruekaCrea.abrir()')+'<main class="crea-library"><section class="crea-section-title"><div><span class="club-kicker">PORTAFOLIO PERSONAL</span><h1>Mis proyectos</h1><p>Solo vos y el equipo docente pueden ver estos trabajos.</p></div><div class="crea-quick"><button onclick="KruekaCrea.nuevo(\'game\')">＋ Juego</button><button onclick="KruekaCrea.nuevo(\'web\')">＋ Web</button><button onclick="KruekaCrea.nuevo(\'design\')">＋ Diseño</button></div></section><div class="crea-project-grid">'+cards+'</div></main>');},
  async duplicar(id){var p=this.projects.find(function(x){return x.id===id})||this.localProjects().find(function(x){return x.id===id});if(!p)return;if(!p.content){try{p=await this.rpc('club_crea_cargar',{p_student:this.sid(),p_device:this.device(),p_project:id})}catch(e){return}}var q=copia(p);q.id=localId();q.title=(q.title||'Proyecto')+' · copia';q.status='draft';q.version=1;q.updated_at=ahora();q.local_only=true;this.saveLocal(q);await this.list();this.verProyectos();},
  async archivar(id){if(!confirm('¿Archivar este proyecto?'))return;try{if(!String(id).startsWith('local-'))await this.rpc('club_crea_archivar',{p_student:this.sid(),p_device:this.device(),p_project:id})}catch(e){}this.removeLocal(id);await this.list();this.verProyectos();},
  async solicitarRevision(){if(!this.current)return;await this.guardar(true);if(String(this.current.id).startsWith('local-')){alert('Necesitás conexión para enviar a revisión.');return}try{var d=await this.rpc('club_crea_solicitar_revision',{p_student:this.sid(),p_device:this.device(),p_project:this.current.id});this.current.status=(d&&d.status)||'review';this.saveLocal(this.current);this.status('Enviado a revisión ✓','ok');alert('¡Listo! Dirección ya puede revisar tu creación.')}catch(e){alert('No se pudo enviar todavía. Probá nuevamente.')}},
  renderWeb:function(){var c=this.current.content||this.baseContent('web');this.current.content=c;var self=this;Club.pinta(this.editorTop('Laboratorio web','<button class="club-secondary" onclick="KruekaCrea.exportWeb()">Descargar HTML</button><button class="club-secondary" onclick="KruekaCrea.solicitarRevision()">Enviar a revisión</button>')+'<main class="crea-editor"><aside class="crea-tools"><span class="club-kicker">PLANTILLAS</span><h2>Empezá con una idea</h2><div class="crea-template-list">'+Object.keys(WEB_TEMPLATES).map(function(k){var t=WEB_TEMPLATES[k];return '<button onclick="KruekaCrea.webTemplate(\''+k+'\')"><span>'+t.icono+'</span><b>'+esc(t.nombre)+'</b></button>'}).join('')+'</div><div class="crea-tip"><b>💡 Probá sin miedo</b><p>Si algo se rompe, elegí otra plantilla. Tu versión anterior queda guardada.</p></div></aside><section class="crea-code-work"><div class="crea-code-tabs" role="tablist" aria-label="Archivos de la página">'+['html','css','js'].map(function(k){return '<button role="tab" aria-selected="'+(self.webTab===k)+'" onclick="KruekaCrea.webShow(\''+k+'\')">'+(k==='html'?'HTML':k==='css'?'CSS':'JavaScript')+'</button>'}).join('')+'<button class="run" onclick="KruekaCrea.webPreview()">▶ Probar</button></div>'+['html','css','js'].map(function(k){return '<div class="crea-code-pane '+(self.webTab===k?'':'hidden')+'" data-pane="'+k+'"><label for="crea-code-'+k+'">Código '+k.toUpperCase()+'</label><textarea id="crea-code-'+k+'" spellcheck="false" oninput="KruekaCrea.webInput(\''+k+'\',this.value)">'+esc(c[k]||'')+'</textarea></div>'}).join('')+'</section><section class="crea-preview"><div class="crea-preview-bar"><div><i></i><i></i><i></i></div><span>Vista segura</span><small>Internet bloqueado dentro de la prueba</small></div><iframe id="crea-web-frame" sandbox="allow-scripts" title="Vista previa de tu página"></iframe><div class="crea-preview-note">La vista se actualiza mientras escribís.</div></section></main>');this.webPreview();},
  webShow:function(k){this.webTab=k;document.querySelectorAll('.crea-code-tabs [role=tab]').forEach(function(b){b.setAttribute('aria-selected',b.textContent.toLowerCase().indexOf(k==='js'?'javascript':k)>=0)});document.querySelectorAll('.crea-code-pane').forEach(function(p){p.classList.toggle('hidden',p.dataset.pane!==k)});var t=document.getElementById('crea-code-'+k);if(t)t.focus();},
  webInput:function(k,v){if(!this.current||this.current.type!=='web')return;this.current.content[k]=v;this.programarGuardado();clearTimeout(this.previewTimer);var self=this;this.previewTimer=setTimeout(function(){self.webPreview()},320);},
  webTemplate:function(k){var t=WEB_TEMPLATES[k];if(!t)return;if(!confirm('¿Usar la plantilla '+t.nombre+'? Reemplazará el código visible.'))return;this.current.content=copia(t);this.programarGuardado();this.renderWeb();},
  webDocument:function(){var c=this.current.content||{},js=String(c.js||'').replace(/<\/script/gi,'<\\/script');return '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data: blob:; media-src data: blob:; style-src \'unsafe-inline\'; script-src \'unsafe-inline\'; font-src data:;"><style>'+String(c.css||'')+'</style></head><body><div id="__kc_error" style="display:none;position:fixed;left:8px;right:8px;bottom:8px;padding:10px;background:#8b1e2d;color:white;font:14px system-ui;border-radius:8px;z-index:9999"></div>'+String(c.html||'')+'<script>window.addEventListener(\'error\',function(e){var b=document.getElementById(\'__kc_error\');b.style.display=\'block\';b.textContent=\'Revisá tu JavaScript: \'+e.message})<\/script><script>'+js+'<\/script></body></html>';},
  webPreview:function(){var f=document.getElementById('crea-web-frame');if(f)f.srcdoc=this.webDocument();},
  exportWeb:function(){descarga((this.current.title||'mi-pagina').replace(/[^a-z0-9áéíóúñ_-]+/gi,'_')+'.html',this.webDocument(),'text/html');},
  patchStaff:function(){if(!Club.pintaPanel||Club.pintaPanel._crea)return;var old=Club.pintaPanel;Club.pintaPanel=function(){var r=old.apply(this,arguments);setTimeout(function(){var v=document.getElementById('view');if(v&&!v.querySelector('[data-crea-review]')){var b=document.createElement('button');b.className='btn';b.dataset.creaReview='1';b.textContent='Revisar creaciones';b.onclick=function(){KruekaCrea.revision()};v.prepend(b)}},0);return r};Club.pintaPanel._crea=true;},
  async revision(){var v=document.getElementById('view');if(!v)return;v.innerHTML='<div class="spinner">Cargando creaciones…</div>';try{var rows=await this.rpc('club_crea_revision',{});rows=Array.isArray(rows)?rows:[];v.innerHTML='<div class="card"><h1>Krueka Crea · revisión</h1><p class="sub">Los proyectos siguen privados hasta que dirección los aprueba.</p></div><div class="crea-review-list">'+(rows.length?rows.map(function(p){var t=TIPOS[p.type]||TIPOS.web;return '<article class="card crea-review"><span>'+t.icono+'</span><div><small>'+esc(p.alumno||'Alumno')+' · '+esc(t.nombre)+'</small><h3>'+esc(p.title||'Sin título')+'</h3><p>Versión '+esc(p.version||1)+'</p></div><div><button class="btn ok sm" onclick="KruekaCrea.revisar(\''+esc(p.id)+'\',\'published\')">Aprobar</button> <button class="btn sec sm" onclick="KruekaCrea.revisar(\''+esc(p.id)+'\',\'draft\')">Pedir mejora</button></div></article>'}).join(''):'<div class="card">No hay proyectos pendientes.</div>')+'</div>'}catch(e){v.innerHTML='<div class="alert err">No se pudieron cargar las creaciones.</div>'}},
  revisar:async function(id,status){var note=prompt(status==='published'?'Mensaje de felicitación (opcional)':'Explicá qué puede mejorar','')||'';try{await this.rpc('club_crea_revisar',{p_project:id,p_status:status,p_note:note.slice(0,500)});this.revision()}catch(e){alert('No se pudo guardar la revisión.')}}
};
window.KruekaCrea=KruekaCrea;
var oldMap=Club.mapa;Club.mapa=function(){var r=oldMap.apply(this,arguments);setTimeout(function(){KruekaCrea.insertEntry()},25);return r;};
function ready(){setTimeout(function(){KruekaCrea.patchStaff()},0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
