/* Retos activos: ordenar, escribir y justificar */
(function(){'use strict';Club.retoOrden={};Club.decisionElegida='';
Club.jugar=function(i){
 var acts=this.lec.actividades||[];if(this.lec.proyecto&&Object.keys(this.lec.proyecto).length&&!this.lec.entrega){this.proyecto();return}if(i>=acts.length){this.fin();return}this.i=i;this.respondiendo=false;var a=acts[i],c=a.contenido||{},pct=Math.round(i/Math.max(acts.length,1)*100),body='';
 if(a.tipo==='ordenar'){if(!this.retoOrden[a.id])this.retoOrden[a.id]=(c.items||[]).slice();body='<div class="club-order-list">'+this.retoOrden[a.id].map(function(x,k){return '<div class="club-order-item"><span class="club-order-num">'+(k+1)+'</span><b>'+esc(x.texto)+'</b><div class="club-order-controls"><button aria-label="Subir" onclick="Club.moverOrden('+k+',-1)">↑</button><button aria-label="Bajar" onclick="Club.moverOrden('+k+',1)">↓</button></div></div>'}).join('')+'</div><div class="club-submit-row"><button class="club-primary" onclick="Club.enviarOrden()">Comprobar mi plan →</button></div>'}
 else if(a.tipo==='respuesta'){body='<textarea id="club-respuesta" class="club-open-answer" maxlength="1000" placeholder="'+esc(c.placeholder||'Explicá tu razonamiento…')+'" oninput="Club.contarRespuesta()"></textarea><div id="club-char-count" class="club-char-count">Mínimo '+esc(c.min_chars||30)+' caracteres</div><div class="club-submit-row"><button class="club-primary" onclick="Club.enviarRespuesta()">Guardar razonamiento →</button></div>'}
 else if(a.tipo==='decision'){body='<div class="club-options">'+(a.opciones||[]).map(function(o,k){return '<button class="club-option" onclick="Club.elegirDecision(\''+esc(o.id)+'\',this)"><span class="club-option-key">'+'ABCD'[k]+'</span><span>'+esc(o.texto||'')+'</span></button>'}).join('')+'</div><textarea id="club-justificacion" class="club-justify" placeholder="Defendé tu decisión: ¿qué consecuencia tendría y por qué es mejor?"></textarea><div class="club-submit-row"><button class="club-primary" onclick="Club.enviarDecision()">Defender decisión →</button></div>'}
 else{body='<div class="club-options">'+(a.opciones||[]).map(function(o,k){return '<button class="club-option" onclick="Club.responder(\''+esc(o.id)+'\')"><span class="club-option-key">'+'ABCD'[k]+'</span>'+(o.emoji?'<span class="club-option-emoji">'+esc(o.emoji)+'</span>':'')+'<span>'+esc(o.texto||'')+'</span></button>'}).join('')+'</div>'}
 this.pinta(this.cabecera(this.lec.titulo)+'<section class="club-quiz-head"><div><span class="club-kicker">FASE 3 · PENSAR Y RESOLVER</span><h1>Reto '+(i+1)+' de '+acts.length+'</h1></div><div class="club-quiz-progress"><i style="width:'+pct+'%"></i></div></section><section class="club-question"><span class="club-type">'+esc((a.tipo||'reto').toUpperCase())+'</span><h2>'+esc(a.pregunta||'')+'</h2>'+(a.pista?'<details class="club-hint"><summary>Necesito una pista</summary><p>💡 '+esc(a.pista)+'</p></details>':'')+'</section>'+body+'<div id="cj-msg" class="club-feedback" aria-live="polite"></div>')
};
Club.moverOrden=function(i,d){var a=this.lec.actividades[this.i],x=this.retoOrden[a.id],j=i+d;if(j<0||j>=x.length)return;var t=x[i];x[i]=x[j];x[j]=t;this.jugar(this.i)};
Club.enviarOrden=function(){var a=this.lec.actividades[this.i],x=this.retoOrden[a.id]||[];this.responder(JSON.stringify(x.map(function(v){return v.id})))};
Club.contarRespuesta=function(){var a=this.lec.actividades[this.i],n=(document.getElementById('club-respuesta').value||'').trim().length,m=(a.contenido&&a.contenido.min_chars)||30;document.getElementById('club-char-count').textContent=n+' / '+m+' caracteres mínimos'};
Club.enviarRespuesta=function(){var a=this.lec.actividades[this.i],v=(document.getElementById('club-respuesta').value||'').trim(),m=(a.contenido&&a.contenido.min_chars)||30;if(v.length<m){document.getElementById('cj-msg').innerHTML='<div class="club-msg error">Desarrollá tu idea con una decisión, una prueba y una mejora.</div>';return}this.responder(v)};
Club.elegirDecision=function(id,b){this.decisionElegida=id;document.querySelectorAll('.club-option').forEach(function(x){x.classList.remove('selected')});b.classList.add('selected')};
Club.enviarDecision=function(){var a=this.lec.actividades[this.i],j=(document.getElementById('club-justificacion').value||'').trim(),m=(a.contenido&&a.contenido.min_chars)||24;if(!this.decisionElegida){document.getElementById('cj-msg').innerHTML='<div class="club-msg error">Primero elegí una decisión.</div>';return}if(j.length<m){document.getElementById('cj-msg').innerHTML='<div class="club-msg error">Defendé tu decisión con una consecuencia o ejemplo.</div>';return}this.responder(JSON.stringify({opcion:this.decisionElegida,justificacion:j}))};
})();
