const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const env={console,JSON,Object,Array,Math,Number,String,Date,setInterval(){return 1},clearInterval(){}};
env.window=env;env.StudioIA={renderCreator(){}};
vm.createContext(env);
for(const p of ['js/club-studio-kits.js','js/club-studio-heroes.js','js/club-studio-game-builder.js','js/club-studio-render-pro.js'])vm.runInContext(read(p),env);
const H=env.StudioHeroes,R=env.StudioRenderPro,G=env.KruekaGameBuilder,K=env.StudioKits;
assert.ok(R&&R.install&&R.decorate&&R.compress);
assert.equal(Object.keys(R.NAMES).length,6);
assert.match(R.SOURCE,/CC0-Public-Domain-Models\/[0-9a-f]{40}\/packs\/quaternius-rpg-characters/);
assert.match(R.LIB,/model-viewer\/4\.1\.0/);
assert.equal(R.validPortrait('data:image/webp;base64,AAAA'),true);
assert.equal(R.validPortrait('javascript:alert(1)'),false);
assert.equal(R.validPortrait('data:image/svg+xml;base64,AAAA'),false);
assert.ok(H.template('knight').renderModel==='warrior');
let cfg=K.read(K.create('hero-manager'));
cfg=G.normalise(cfg);
cfg.world.map.push({id:'custom-tower',type:'tower',x:8,y:2,scale:1,rot:0,name:'Mi torre'});
cfg.heroes[0].portrait='data:image/webp;base64,AAAA';
cfg.heroes[0].renderModel='cleric';
let kept=H.clean(cfg);
assert.equal(kept.world.map.length,5,'Editar héroe no debe borrar el mapa');
assert.equal(kept.heroes[0].renderModel,'cleric');
assert.equal(kept.heroes[0].portrait,'data:image/webp;base64,AAAA');
const rejected=H.cleanHero({...kept.heroes[0],portrait:'data:image/svg+xml;base64,AAAA',renderModel:'../../secret.glb'});
assert.equal(rejected.portrait,'');assert.equal(rejected.renderModel,'warrior');
const html=H.art(kept.heroes[0]);
assert.ok(html.includes('href="data:image/webp;base64,AAAA"'));
const files=K.create('hero-manager');
const runtimeFiles={...files,'game-config.js':K.configFile(kept)};
assert.ok(Object.values(runtimeFiles).reduce((n,s)=>n+s.length,0)<220000);
new vm.Script(files['hero.js']);
assert.ok(read('app.html').includes('club-studio-render-pro.js?v=20261009c'));
assert.ok(read('js/club-studio-heroes.js').includes('StudioRenderPro.decorate(studio,el,cfg)'));
console.log('PASS: Render Pro, modelos GLB CC0, importación WebP validada, mundo preservado y exportación compatible.');
