const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const env={console,Math,JSON,Object,Array,Number,String,Date,Set};env.window=env;vm.createContext(env);
const modules=['js/club-studio-kits.js','js/club-studio-3d.js','js/club-studio-missions.js','js/club-studio-forge.js','js/club-studio-showcase.js'];
for(const file of modules)vm.runInContext(read(file),env);
const kits=env.StudioKits,mission=env.StudioMissions,files=kits.create('space3d'),config=kits.read(files);
assert.equal(config.kind,'space3d');
assert.equal(Object.keys(files).length,5);
for(const file of ['game.js','game-config.js'])new vm.Script(files[file]);
assert.ok(Object.values(files).every(s=>s.length<=120000));
assert.ok(Object.values(files).reduce((n,s)=>n+s.length,0)<65000,'La misión cabe en el presupuesto de entrada de IA');
assert.ok(!/https?:\/\//i.test(Object.values(files).join('')),'El juego es autónomo');
assert.equal(config.objects.filter(o=>o.type==='cell').length,3);
assert.equal(config.objects.filter(o=>o.type==='terminal').length,2);
assert.equal(config.objects.filter(o=>o.type==='drone').length,3);
const copy=kits.create('space3d');files['game-config.js']=kits.configFile({...config,lighting:'alert'});
assert.equal(kits.read(files).lighting,'alert');assert.equal(kits.read(copy).lighting,'cryo');
assert.equal(copy['game.js'],files['game.js'],'Cambiar reglas conserva el motor');
const malformed=mission.normalise({title:'x'.repeat(100),lighting:'unknown',weaponColor:'red',speed:Infinity,lives:-5,seconds:9999,droneSpeed:99,objects:[null,...Array.from({length:30},()=>({id:'duplicate',type:'unknown',x:999,z:-999,size:-2,height:99,color:'red',label:'y'.repeat(50)}))]});
assert.equal(malformed.objects.length,24);assert.equal(new Set(malformed.objects.map(o=>o.id)).size,24);
assert.ok(malformed.objects.every(o=>/^[a-z0-9-]{1,32}$/.test(o.id)&&o.x>=-3&&o.x<=3&&o.z>=-14&&o.z<=13&&o.size>=.4&&o.size<=1.8&&o.height>=.5&&o.height<=2.4&&o.label.length<=32&&/^#[0-9a-f]{6}$/i.test(o.color)));
assert.equal(malformed.title.length,60);assert.equal(malformed.lives,1);assert.equal(malformed.seconds,600);assert.equal(malformed.droneSpeed,2);assert.equal(malformed.speed,4);assert.equal(malformed.lighting,'cryo');
assert.equal(JSON.stringify(mission.normalise(malformed)),JSON.stringify(malformed));
const serialized={Set,Number,String,Math,input:malformed};vm.createContext(serialized);vm.runInContext(files['game.js'].split('\n(function runtime')[0],serialized);
assert.equal(JSON.stringify(vm.runInContext('normalise(input)',serialized)),JSON.stringify(malformed),'La copia exportada conserva la validación');
for(const id of ['explore3d','cinematic3d','neon-rift'])assert.ok(kits.create(id)['game.js'].length>5000,'Conserva '+id);
vm.runInContext(read('js/club-studio-missions.js'),env);assert.equal(kits.catalog.filter(k=>k.id==='space3d').length,1,'La carga repetida no duplica el kit');
const app=read('app.html');assert.ok(app.indexOf('club-studio-kits.js')<app.indexOf('club-studio-missions.js'));assert.ok(app.indexOf('club-studio-missions.js')<app.indexOf('club-studio-ai.js'));
console.log('PASS: misión autónoma, presupuesto IA, copia independiente, configuración exportada, límites y convivencia con las otras bases.');
