const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const e={console,Math,JSON,Object,Array,Number,String,Date};e.window=e;vm.createContext(e);
for(const file of ['js/club-studio-kits.js','js/club-studio-3d.js','js/club-studio-forge.js','js/club-studio-showcase.js'])vm.runInContext(read(file),e);
const base=e.StudioKits;
assert.ok(base.catalog.some(x=>x.id==='cinematic3d'));
const files=base.create('cinematic3d');
assert.equal(Object.keys(files).length,5);
assert.ok(files['game.js'].includes('cinemaScene();'));
assert.ok(files['game.js'].includes('cinematicSetup();'));
assert.ok(files['index.html'].includes('id="interact"'));
assert.ok(files['index.html'].includes('id="dialogue"'));
new vm.Script(files['game.js']);new vm.Script(files['game-config.js']);
const config=base.read(files);assert.equal(config.kind,'cinematic3d');
assert.equal(config.characters.hero.name,'Alex Vega');
assert.equal(Object.keys(config.characters).length,3);
assert.equal(config.environment.district,'city');
assert.equal(config.objects.filter(x=>x.type==='crystal').length,3);
assert.ok(Object.values(files).every(s=>s.length<120000));
assert.ok(Object.values(files).reduce((a,s)=>a+s.length,0)<65000,'Compatible con presupuesto de código para IA');
assert.ok(!/https?:\/\//i.test(Object.values(files).join('')),'Juego completamente autónomo');
const newConfig=e.StudioForge.clean({...config,characters:{...config.characters,hero:{...config.characters.hero,name:'Alex',height:99,skin:'red'}},environment:{district:'unknown',weather:'rain',light:'sunset'}});
assert.equal(newConfig.characters.hero.name,'Alex');assert.equal(newConfig.characters.hero.height,1.17);
assert.match(newConfig.characters.hero.skin,/^#[0-9a-f]{6}$/i);
assert.equal(newConfig.environment.district,'city');
assert.equal(newConfig.environment.weather,'rain');
assert.ok(base.create('explore3d')['game.js'].length>5000);
assert.ok(base.create('neon-rift')['game.js'].length>10000);
assert.ok(read('app.html').includes('club-studio-forge.js?v=20261008a'));
console.log('PASS: personajes, escena, movimientos, diálogo, copia independiente, límites, 3D existente y código compilable.');
