const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const env={console,Math,Date,JSON,Object,Array,String,Number,setInterval(){return 1;},clearInterval(){}};
env.window=env;vm.createContext(env);
for(const p of ['js/club-studio-kits.js','js/club-studio-heroes.js','js/club-studio-game-builder.js','js/club-studio-render-pro.js'])vm.runInContext(read(p),env);
const K=env.StudioKits,H=env.StudioHeroes,R=env.StudioRenderPro,G=env.KruekaGameBuilder;
assert.ok(R.protagonistFiles&&R.activateProtagonist&&R.capturePortrait,'Existe la promoción explícita de héroes');
let files=K.create('hero-manager'),cfg=K.read(files);
cfg.world={biome:'forest',map:[{id:'hero-start',type:'hero',name:'Inicio',x:2,y:4,scale:1,rot:0},{id:'tree-old',type:'tree',name:'Pino',x:7,y:3,scale:1,rot:0}],mission:'Rescatá al explorador'};
cfg.combat={mode:'turn',enemies:8};
files['game-config.js']=K.configFile(cfg);
const rawPortrait='data:image/webp;base64,AAAA';
const calls=[];
const studio={files,cloudReady:true,busy:false,heroSelected:'hero-3',undo:[],validFiles(files){return K.read?Object.keys(files).length:1},checkpoint(){this.undo.push({...this.files})},changed(){calls.push('changed')},refreshAll(){calls.push('refresh')},lock(){calls.push('lock')}};
const old=files['hero.js'];
const after=R.protagonistFiles(studio,'hero-3','wizard',rawPortrait);
assert.equal(K.read(after.files).active,'hero-3');
assert.equal(K.read(after.files).heroes[2].portrait,rawPortrait);
assert.equal(K.read(after.files).heroes[2].renderModel,'wizard');
assert.equal(K.read(after.files).world.map[0].name,K.read(after.files).heroes[2].name);
assert.equal(K.read(after.files).world.map[1].name,'Pino');
assert.equal(K.read(after.files).world.mission,'Rescatá al explorador');
assert.equal(K.read(after.files).combat.enemies,8);
assert.ok(after.files['hero.js'].includes('Retrato importado del héroe'));
assert.ok(after.files['hero.js'].includes('renderModel:choice'));
new vm.Script(after.files['hero.js']);
assert.equal(studio.files['hero.js'],old,'Previsualización no debe alterar archivos antes de confirmar');
assert.throws(()=>R.protagonistFiles(studio,'missing','wizard',rawPortrait),/No se encontró/);
assert.throws(()=>R.protagonistFiles(studio,'hero-1','hacker',rawPortrait),/modelo/);
assert.throws(()=>R.protagonistFiles(studio,'hero-1','warrior','https://evil.test/image'),/captura/);
const committed=R.activateProtagonist(studio,'hero-3','wizard',rawPortrait);
assert.equal(studio.undo.length,1);
assert.equal(K.read(studio.files).active,'hero-3');
assert.equal(studio.heroSelected,'hero-3');
assert.equal(calls.join(','),'changed,refresh,lock');
const hero=K.read(studio.files).heroes[2];
assert.ok(H.art(hero).includes('data:image/webp;base64,AAAA'));
const map=G.normalise(K.read(studio.files));assert.equal(map.world.map.length,2);
const blank=K.create('hero-manager');const fresh={...studio,files:blank,undo:[]};
const promoted=R.protagonistFiles(fresh,'hero-1','warrior',rawPortrait);
assert.ok(K.read(promoted.files).world.map.some(o=>o.type==='hero'));
assert.equal(K.read(promoted.files).active,'hero-1');
assert.ok(read('app.html').includes('club-studio-render-pro.js?v=20261009c'));
console.log('PASS: promoción 3D del héroe, retrato en colección, compatibilidad con juegos anteriores, mapa/combate intactos y Deshacer.');
