const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const studio={files:{},title:'Mi juego',draft:'Hacé un castillo',renderAIStatus(){return 'ok'}};
const context={window:null,console,setInterval(){return 1},clearInterval(){}};
context.window=context;context.StudioIA=studio;context.StudioKits={read:()=>({kind:'hero-manager'})};
vm.createContext(context);vm.runInContext(read('js/club-studio-alt-help.js'),context);
const helper=context.StudioAltHelp;
assert.ok(helper&&helper.install);
assert.equal(helper.CHAT_URL,'https://chatgpt.com/','No debe abrir una conversación privada del profesor');
assert.equal(context.StudioIA.__altHelpInstalled,true);
const prompt=helper.promptFor(studio,'Construí una aldea');
assert.match(prompt,/Construí una aldea/);assert.match(prompt,/Mi juego/);
assert.ok(!prompt.includes('studentId')&&!prompt.includes('deviceId'));
assert.equal(helper.guideFor('hero-manager').length,4);
assert.match(helper.guideFor('hero-manager')[0],/Personajes/);
assert.match(read('app.html'),/club-studio-alt-help.js\?v=20261009a/);
assert.match(read('club/club-studio.css'),/ks-alt-help/);
assert.doesNotMatch(read('js/club-studio-alt-help.js'),/chatgpt\.com\/c\/[0-9a-z-]+/);
console.log('PASS: navegación sin API, prompt sin identificadores, cuenta individual y guía local.');
