const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{stripTypeScriptTypes}=require('node:module');
const source=fs.readFileSync(require('node:path').join(__dirname,'index.ts'),'utf8').replace(/^import .*;\n/gm,'');
const student='11111111-1111-4111-8111-111111111111',project='22222222-2222-4222-8222-222222222222',rows=new Map(),bucket=new Map(),env={SUPABASE_URL:'https://test.invalid',SUPABASE_ANON_KEY:'public',SUPABASE_SERVICE_ROLE_KEY:'server'};let handler,upstreamCalls=0,bucketCalls=0,replyMode='ok',quotaBlock=false,settled=[],reserved=[];
const pub={rpc:async(name,a)=>{
 if(a.p_device!=='test-device')return {error:{message:'Dispositivo no autorizado'}};
 if(name==='club_crea_listar')return {data:Array.from(rows.values()).map(x=>({id:x.id,type:'web',title:x.title,status:x.status}))};
 if(name==='club_crea_guardar'){const p={id:a.p_project||project,title:a.p_title,content:a.p_content,status:'draft',updated_at:'today'};rows.set(p.id,p);return {data:p};}
 if(name==='club_crea_cargar')return rows.has(a.p_project)?{data:rows.get(a.p_project)}:{error:{message:'Proyecto no encontrado'}};
 if(name==='club_crea_solicitar_revision'){rows.get(a.p_project).status='review';return {data:{ok:true}};}
 throw new Error('Unknown RPC '+name);
}};
const admin={rpc:async(name,a)=>{if(name==='club_studio_ai_status')return {data:{usedToday:2,dailyLimit:12,budgetAvailable:true}};if(name==='club_studio_ai_reserve'){reserved.push(a);return {data:quotaBlock?{ok:false,code:'budget',error:'Cupo agotado'}:{ok:true,requestId:'reserve'}}}if(name==='club_studio_ai_finish'){settled.push(a);return {data:null}}throw new Error(name)},storage:{listBuckets:async()=>(bucketCalls++,{data:[{name:'krueka-studio'}]}),from:()=>({download:async path=>bucket.has(path)?{data:new Blob([bucket.get(path)])}:{error:{message:'Object not found'}},upload:async(path,data)=>{bucketCalls++;bucket.set(path,await data.text());return {data:{}}}})}};
const context=vm.createContext({console,Response,Request,Blob,AbortSignal,TextEncoder,Deno:{env:{get:k=>env[k]},serve:h=>handler=h},createClient:(_url,key)=>key==='server'?admin:pub,fetch:async(url,options)=>{upstreamCalls++;assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);assert.equal(body.model,'gpt-6-luna');assert.equal(body.service_tier,'default');assert.equal(body.store,false);assert.equal(body.max_output_tokens,6000);assert.equal(body.reasoning.effort,'none');assert.equal(body.text.format.strict,true);assert.ok(body.text.format.schema.required.includes('patches'));assert.ok(!body.tools);assert.ok(!options.body.includes('student_id'));if(replyMode==='timeout')throw new Error('Timeout');if(replyMode==='auth')return new Response('{}',{status:401});const usesPatches=['patch','sequence','missing','blank','atomic','too-many'].includes(replyMode);let patches=usesPatches?[{path:'style.css',find:'body{}',replace:'body{color:red}'}]:[];if(replyMode==='sequence')patches=[{path:'style.css',find:'body{}',replace:'body{color:blue}'},{path:'style.css',find:'body{color:blue}',replace:'body{color:red}'}];if(replyMode==='missing')patches[0].path='missing.css';if(replyMode==='blank')patches[0].find='';if(replyMode==='atomic')patches.push({path:'style.css',find:'absent',replace:'no'});if(replyMode==='too-many')patches=Array(33).fill(patches[0]);const result=JSON.stringify({summary:'Cambio',files:usesPatches?[]:[{path:replyMode==='invalid'?'../bad.js':'style.css',content:'body{color:red}'}],patches,test:'Probá'});return new Response(JSON.stringify({status:replyMode==='partial'?'incomplete':'completed',usage:{input_tokens:1000,output_tokens:2000},output:[{content:[{type:'output_text',text:result}]}]}),{status:200});}});
vm.runInContext(stripTypeScriptTypes(source),context);
const call=async b=>{const r=await handler(new Request('https://test.invalid',{method:'POST',body:JSON.stringify({studentId:student,deviceId:'test-device',...b})}));return {status:r.status,...await r.json()};};
(async()=>{
 assert.equal((await call({action:'load'})).project,null);const files={'index.html':'<!doctype html><h1>Prueba</h1>','style.css':'body{}'};
 const history=[{role:'user',text:'Agregá estrellas',pending:true},{role:'ai',text:'Cambio',artifact:{title:'Prueba',files:['style.css']}}];
 assert.equal((await call({action:'save',files,history,draft:'Idea sin enviar',title:'Anterior'})).ok,true);const legacy=(await call({action:'load'})).project;assert.equal(legacy.draft,'Idea sin enviar');assert.equal(legacy.history[0].pending,true);assert.equal(legacy.history[1].artifact.title,'Prueba');
 assert.equal((await call({action:'save',projectId:'new',files,history,draft:'Otro',title:'Nuevo'})).id,project);assert.equal((await call({action:'load',projectId:project})).project.draft,'Otro');
 assert.equal((await call({action:'list'})).projects.length,2);assert.equal((await call({action:'submit',projectId:project})).submitted,true);
 const count=bucketCalls;assert.equal((await call({action:'load',deviceId:'wrong-device'})).ok,false);assert.equal(bucketCalls,count);
 const unavailable=await call({action:'ai',prompt:'Agregá monedas',files});assert.equal(unavailable.status,503);assert.equal(unavailable.setupRequired,true);assert.equal(upstreamCalls,0);
 env.OPENAI_API_KEY='test-only';assert.equal((await call({action:'status'})).ai.ready,false);env.STUDIO_AI_ENABLED='true';assert.equal((await call({action:'status'})).ai.ready,true);
 const ai=await call({action:'ai',prompt:'Cambiá color',files,model:'gpt-6-astra'});assert.equal(ai.files['style.css'],'body{color:red}');assert.match(ai.model,/gpt-6-luna/);assert.ok(reserved[0].p_micros>=3000);assert.equal(settled.at(-1).p_actual_micros,1100);
 quotaBlock=true;const before=upstreamCalls;assert.equal((await call({action:'ai',prompt:'Cambiá color',files})).status,429);assert.equal(upstreamCalls,before);quotaBlock=false;
 for(const mode of ['partial','invalid']){replyMode=mode;const d=await call({action:'ai',prompt:'Cambiá color',files});assert.equal(d.ok,false);assert.equal(d.files,undefined);assert.equal(d.ai.usedToday,2);assert.equal(settled.at(-1).p_actual_micros,1100)}

 for(const mode of ['patch','sequence']){replyMode=mode;const d=await call({action:'ai',prompt:'Cambiá color',files});assert.equal(d.files['style.css'],'body{color:red}');assert.equal(files['style.css'],'body{}');}
 for(const mode of ['missing','blank','atomic','too-many']){replyMode=mode;const d=await call({action:'ai',prompt:'Cambiá color',files});assert.equal(d.ok,false);assert.equal(d.files,undefined);assert.equal(files['style.css'],'body{}');assert.equal(d.ai.usedToday,2);}
 replyMode='patch';const ambiguous=await call({action:'ai',prompt:'Cambiá color',files:{...files,'style.css':'body{}body{}'}});assert.equal(ambiguous.ok,false);assert.equal(ambiguous.files,undefined);
 const plan=await call({action:'ai',mode:'plan',prompt:'Qué mejorarías',files});assert.equal(plan.ok,true);assert.equal(Object.keys(plan.files).length,0);
 replyMode='timeout';assert.equal((await call({action:'ai',prompt:'Cambiá color',files})).ok,false);assert.equal(settled.at(-1).p_actual_micros,null);
 replyMode='auth';assert.equal((await call({action:'ai',prompt:'Cambiá color',files})).setupRequired,true);assert.equal(settled.at(-1).p_actual_micros,0);
 assert.equal((await call({action:'unknown'})).status,400);assert.equal((await call({action:'ai',prompt:'mi correo ejemplo@test.com',files})).status,400);
 const final=upstreamCalls;assert.equal((await call({action:'ai',prompt:'Cambiá color',files:{...files,'info.txt':'ejemplo@test.com'}})).status,400);assert.equal(upstreamCalls,final);
 console.log('PASS: fragmentos exactos/secuenciales; rechazo atómico de ambigüedad/ruta/fragmento inválido; plan sin cambios; contador en errores; historial, borradores y tarjetas; proyectos privados; API desactivada; modelo fijo; reserva previa; cuotas; consumo; respuestas incompletas/invalidas; fallo sin reintentos ni cambios parciales.');
})().catch(e=>{console.error(e);process.exit(1)});
