-- 040 · Krueka Crea: proyectos privados, versiones, recursos y revisión
-- El acceso infantil exige alumno activo de B.E.I. y dispositivo vinculado.

create table public.club_creator_projects (
 id uuid primary key default gen_random_uuid(),student_id uuid not null references public.club_students(id) on delete cascade,institution_id uuid not null references public.institutions(id) on delete cascade,
 type text not null check(type in('game','web','design')),title text not null check(char_length(title) between 1 and 80),content jsonb not null default '{}'::jsonb check(jsonb_typeof(content)='object'),status text not null default 'draft' check(status in('draft','review','published','archived')),version integer not null default 1 check(version>0),
 review_note text check(review_note is null or char_length(review_note)<=500),reviewed_by uuid references public.profiles(id) on delete set null,reviewed_at timestamptz,published_at timestamptz,last_saved_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.club_creator_versions (
 id bigint generated always as identity primary key,project_id uuid not null references public.club_creator_projects(id) on delete cascade,student_id uuid not null references public.club_students(id) on delete cascade,version integer not null check(version>0),title text not null check(char_length(title) between 1 and 80),content jsonb not null check(jsonb_typeof(content)='object'),created_at timestamptz not null default now(),unique(project_id,version)
);
create table public.club_creator_assets (
 id uuid primary key default gen_random_uuid(),student_id uuid not null references public.club_students(id) on delete cascade,project_id uuid references public.club_creator_projects(id) on delete cascade,kind text not null check(kind in('sprite','background','sound','palette')),name text not null check(char_length(name) between 1 and 60),definition jsonb not null default '{}'::jsonb check(jsonb_typeof(definition)='object'),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.club_creator_templates (
 slug text primary key check(slug~'^[a-z0-9-]{3,50}$'),type text not null check(type in('game','web','design')),level text not null default 'all' check(level in('all','peques','mayores')),title text not null check(char_length(title) between 1 and 80),description text not null default '' check(char_length(description)<=240),content jsonb not null default '{}'::jsonb check(jsonb_typeof(content)='object'),active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
comment on table public.club_creator_projects is 'Proyectos privados creados por estudiantes del Club en Krueka Crea.';
comment on table public.club_creator_versions is 'Historial acotado de versiones de cada proyecto creativo.';
comment on table public.club_creator_assets is 'Recursos creativos estructurados: sprites, fondos, sonidos y paletas.';
comment on table public.club_creator_templates is 'Plantillas aprobadas por el equipo para iniciar proyectos sin recursos externos.';
create index club_creator_projects_student_updated_idx on public.club_creator_projects(student_id,updated_at desc) where status<>'archived';
create index club_creator_projects_institution_status_idx on public.club_creator_projects(institution_id,status,updated_at desc);
create index club_creator_projects_reviewed_by_idx on public.club_creator_projects(reviewed_by) where reviewed_by is not null;
create index club_creator_versions_project_idx on public.club_creator_versions(project_id,version desc);
create index club_creator_versions_student_idx on public.club_creator_versions(student_id);
create index club_creator_assets_student_idx on public.club_creator_assets(student_id,updated_at desc);
create index club_creator_assets_project_idx on public.club_creator_assets(project_id) where project_id is not null;
create index club_creator_templates_active_idx on public.club_creator_templates(active,level,type,sort_order);
alter table public.club_creator_projects enable row level security;alter table public.club_creator_projects force row level security;
alter table public.club_creator_versions enable row level security;alter table public.club_creator_versions force row level security;
alter table public.club_creator_assets enable row level security;alter table public.club_creator_assets force row level security;
alter table public.club_creator_templates enable row level security;alter table public.club_creator_templates force row level security;
revoke all on table public.club_creator_projects from public,anon,authenticated;revoke all on table public.club_creator_versions from public,anon,authenticated;revoke all on table public.club_creator_assets from public,anon,authenticated;revoke all on table public.club_creator_templates from public,anon,authenticated;revoke all on sequence public.club_creator_versions_id_seq from public,anon,authenticated;
insert into public.club_creator_templates(slug,type,level,title,description,content,sort_order) values
('game-stars','game','peques','Atrapa las estrellas','Mover, sumar puntos y ganar.',jsonb_build_object('jugador','🚀','premio','⭐','meta',5),10),
('game-forest','game','all','Aventura del bosque','Un mundo para transformar con reglas propias.',jsonb_build_object('jugador','🦊','premio','🍓','meta',7),20),
('web-neon','web','mayores','Perfil neón','Una página personal con estilo, botones y JavaScript.',jsonb_build_object('tema','neon'),30),
('design-robot','design','peques','Robot píxel','Plantilla de personaje 16 por 16.',jsonb_build_object('size',16,'template','robot'),40)
on conflict(slug) do update set type=excluded.type,level=excluded.level,title=excluded.title,description=excluded.description,content=excluded.content,sort_order=excluded.sort_order,active=true,updated_at=now();

create or replace function public.club_crea_estudiante_valido(p_student uuid,p_device text) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.club_students s where s.id=p_student and s.activo and s.institution_id='88c4af03-bdce-48e6-b548-b6904fe704bd'::uuid and p_device is not null and char_length(p_device) between 8 and 120 and s.device_id=p_device)
$$;
revoke all on function public.club_crea_estudiante_valido(uuid,text) from public,anon,authenticated;

create or replace function public.club_crea_listar(p_student uuid,p_device text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_result jsonb;begin
 if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;
 select coalesce(jsonb_agg(q.item order by q.updated_at desc),'[]'::jsonb) into v_result from(select p.updated_at,jsonb_build_object('id',p.id,'type',p.type,'title',p.title,'status',p.status,'version',p.version,'review_note',p.review_note,'updated_at',p.updated_at,'published_at',p.published_at)item from public.club_creator_projects p where p.student_id=p_student and p.status<>'archived' order by p.updated_at desc limit 30)q;return v_result;
end;$$;
create or replace function public.club_crea_cargar(p_student uuid,p_device text,p_project uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare p public.club_creator_projects;begin
 if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;
 select * into p from public.club_creator_projects where id=p_project and student_id=p_student and status<>'archived';if p.id is null then raise exception 'Proyecto no encontrado.';end if;
 return jsonb_build_object('id',p.id,'type',p.type,'title',p.title,'content',p.content,'status',p.status,'version',p.version,'review_note',p.review_note,'updated_at',p.updated_at,'published_at',p.published_at);
end;$$;
create or replace function public.club_crea_guardar(p_student uuid,p_device text,p_project uuid,p_type text,p_title text,p_content jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_inst uuid;v_row public.club_creator_projects%rowtype;v_project uuid;v_version integer;v_title text;begin
 if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;if p_type not in('game','web','design') then raise exception 'Tipo de proyecto no valido.';end if;
 v_title:=btrim(coalesce(p_title,''));if char_length(v_title) not between 1 and 80 then raise exception 'El nombre debe tener entre 1 y 80 caracteres.';end if;if jsonb_typeof(coalesce(p_content,'null'::jsonb))<>'object' then raise exception 'Contenido de proyecto no valido.';end if;if octet_length(p_content::text)>300000 then raise exception 'El proyecto supera el limite de 300 KB.';end if;
 select institution_id into v_inst from public.club_students where id=p_student;
 if p_project is null then
  if(select count(*) from public.club_creator_projects where student_id=p_student and status<>'archived')>=30 then raise exception 'Alcanzaste el limite de 30 proyectos activos. Archiva uno para continuar.';end if;
  insert into public.club_creator_projects(student_id,institution_id,type,title,content)values(p_student,v_inst,p_type,v_title,p_content)returning id,version into v_project,v_version;
  insert into public.club_creator_versions(project_id,student_id,version,title,content)values(v_project,p_student,v_version,v_title,p_content);
 else
  select * into v_row from public.club_creator_projects where id=p_project and student_id=p_student and status<>'archived' for update;if v_row.id is null then raise exception 'Proyecto no encontrado.';end if;if v_row.type<>p_type then raise exception 'No se puede cambiar el tipo del proyecto.';end if;v_project:=v_row.id;
  if v_row.title is distinct from v_title or v_row.content is distinct from p_content then v_version:=v_row.version+1;update public.club_creator_projects set title=v_title,content=p_content,version=v_version,status='draft',review_note=null,reviewed_by=null,reviewed_at=null,published_at=null,last_saved_at=now(),updated_at=now() where id=v_project;insert into public.club_creator_versions(project_id,student_id,version,title,content)values(v_project,p_student,v_version,v_title,p_content);else v_version:=v_row.version;update public.club_creator_projects set last_saved_at=now() where id=v_project;end if;
 end if;
 delete from public.club_creator_versions old where old.project_id=v_project and old.id not in(select keep.id from public.club_creator_versions keep where keep.project_id=v_project order by keep.version desc limit 100);select * into v_row from public.club_creator_projects where id=v_project;return jsonb_build_object('id',v_row.id,'type',v_row.type,'title',v_row.title,'status',v_row.status,'version',v_row.version,'updated_at',v_row.updated_at);
end;$$;
create or replace function public.club_crea_archivar(p_student uuid,p_device text,p_project uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_id uuid;begin if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;update public.club_creator_projects set status='archived',updated_at=now() where id=p_project and student_id=p_student and status<>'archived' returning id into v_id;if v_id is null then raise exception 'Proyecto no encontrado.';end if;return jsonb_build_object('ok',true,'id',v_id,'status','archived');end;$$;
create or replace function public.club_crea_solicitar_revision(p_student uuid,p_device text,p_project uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_id uuid;begin if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;update public.club_creator_projects set status='review',review_note=null,reviewed_by=null,reviewed_at=null,updated_at=now() where id=p_project and student_id=p_student and status='draft' and octet_length(content::text)>2 returning id into v_id;if v_id is null then raise exception 'El proyecto no esta listo para revision.';end if;return jsonb_build_object('ok',true,'id',v_id,'status','review');end;$$;
create or replace function public.club_crea_versiones(p_student uuid,p_device text,p_project uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_result jsonb;begin if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;if not exists(select 1 from public.club_creator_projects where id=p_project and student_id=p_student and status<>'archived') then raise exception 'Proyecto no encontrado.';end if;select coalesce(jsonb_agg(jsonb_build_object('version',v.version,'title',v.title,'created_at',v.created_at)order by v.version desc),'[]'::jsonb) into v_result from public.club_creator_versions v where v.project_id=p_project and v.student_id=p_student;return v_result;end;$$;
create or replace function public.club_crea_restaurar(p_student uuid,p_device text,p_project uuid,p_version integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_project public.club_creator_projects%rowtype;v_old public.club_creator_versions%rowtype;v_new_version integer;begin if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;select * into v_project from public.club_creator_projects where id=p_project and student_id=p_student and status<>'archived' for update;if v_project.id is null then raise exception 'Proyecto no encontrado.';end if;select * into v_old from public.club_creator_versions where project_id=p_project and student_id=p_student and version=p_version;if v_old.id is null then raise exception 'Version no encontrada.';end if;v_new_version:=v_project.version+1;update public.club_creator_projects set title=v_old.title,content=v_old.content,version=v_new_version,status='draft',review_note=null,reviewed_by=null,reviewed_at=null,published_at=null,last_saved_at=now(),updated_at=now() where id=p_project;insert into public.club_creator_versions(project_id,student_id,version,title,content)values(p_project,p_student,v_new_version,v_old.title,v_old.content);return jsonb_build_object('id',p_project,'type',v_project.type,'title',v_old.title,'content',v_old.content,'status','draft','version',v_new_version,'updated_at',now());end;$$;
create or replace function public.club_crea_plantillas(p_student uuid,p_device text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_level text;v_result jsonb;begin if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;select coalesce(g.nivel,'peques') into v_level from public.club_students s left join public.club_groups g on g.id=s.group_id where s.id=p_student;select coalesce(jsonb_agg(jsonb_build_object('slug',t.slug,'type',t.type,'title',t.title,'description',t.description,'content',t.content)order by t.sort_order,t.title),'[]'::jsonb) into v_result from public.club_creator_templates t where t.active and t.level in('all',v_level);return v_result;end;$$;
create or replace function public.club_crea_assets_listar(p_student uuid,p_device text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_result jsonb;begin if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'project_id',a.project_id,'kind',a.kind,'name',a.name,'definition',a.definition,'updated_at',a.updated_at)order by a.updated_at desc),'[]'::jsonb) into v_result from public.club_creator_assets a where a.student_id=p_student;return v_result;end;$$;
create or replace function public.club_crea_asset_guardar(p_student uuid,p_device text,p_asset uuid,p_project uuid,p_kind text,p_name text,p_definition jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_id uuid;v_name text;begin if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;if p_kind not in('sprite','background','sound','palette') then raise exception 'Tipo de recurso no valido.';end if;v_name:=btrim(coalesce(p_name,''));if char_length(v_name) not between 1 and 60 then raise exception 'Nombre de recurso no valido.';end if;if jsonb_typeof(coalesce(p_definition,'null'::jsonb))<>'object' or octet_length(p_definition::text)>160000 then raise exception 'Recurso no valido o demasiado grande.';end if;if p_project is not null and not exists(select 1 from public.club_creator_projects where id=p_project and student_id=p_student and status<>'archived') then raise exception 'Proyecto no encontrado.';end if;if p_asset is null then if(select count(*) from public.club_creator_assets where student_id=p_student)>=60 then raise exception 'Alcanzaste el limite de 60 recursos.';end if;insert into public.club_creator_assets(student_id,project_id,kind,name,definition)values(p_student,p_project,p_kind,v_name,p_definition)returning id into v_id;else update public.club_creator_assets set project_id=p_project,kind=p_kind,name=v_name,definition=p_definition,updated_at=now() where id=p_asset and student_id=p_student returning id into v_id;if v_id is null then raise exception 'Recurso no encontrado.';end if;end if;return jsonb_build_object('ok',true,'id',v_id,'kind',p_kind,'name',v_name);end;$$;
create or replace function public.club_crea_asset_borrar(p_student uuid,p_device text,p_asset uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_id uuid;begin if not public.club_crea_estudiante_valido(p_student,p_device) then raise exception 'Dispositivo no autorizado para este alumno.';end if;delete from public.club_creator_assets where id=p_asset and student_id=p_student returning id into v_id;if v_id is null then raise exception 'Recurso no encontrado.';end if;return jsonb_build_object('ok',true,'id',v_id);end;$$;
create or replace function public.club_crea_revision() returns jsonb language plpgsql security definer set search_path='' as $$
declare v_inst uuid;v_result jsonb;begin select p.institution_id into v_inst from public.profiles p where p.id=auth.uid() and p.activo and p.role in('admin','director');if v_inst is null then raise exception 'Acceso denegado.';end if;select coalesce(jsonb_agg(q.item order by q.updated_at desc),'[]'::jsonb) into v_result from(select pr.updated_at,jsonb_build_object('id',pr.id,'student_id',s.id,'alumno',s.nombre,'type',pr.type,'title',pr.title,'content',pr.content,'status',pr.status,'version',pr.version,'review_note',pr.review_note,'updated_at',pr.updated_at)item from public.club_creator_projects pr join public.club_students s on s.id=pr.student_id where pr.institution_id=v_inst and pr.status='review' order by pr.updated_at desc limit 100)q;return v_result;end;$$;
create or replace function public.club_crea_revisar(p_project uuid,p_status text,p_note text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_inst uuid;v_id uuid;v_note text;begin select p.institution_id into v_inst from public.profiles p where p.id=auth.uid() and p.activo and p.role in('admin','director');if v_inst is null then raise exception 'Acceso denegado.';end if;if p_status not in('published','draft') then raise exception 'Estado de revision no valido.';end if;v_note:=nullif(left(btrim(coalesce(p_note,'')),500),'');if p_status='draft' and v_note is null then v_note:='Revisa el proyecto con tu profe y vuelve a enviarlo.';end if;update public.club_creator_projects set status=p_status,review_note=v_note,reviewed_by=auth.uid(),reviewed_at=now(),published_at=case when p_status='published' then now() else null end,updated_at=now() where id=p_project and institution_id=v_inst and status='review' returning id into v_id;if v_id is null then raise exception 'Proyecto pendiente no encontrado.';end if;insert into public.audit_log(actor_id,accion,entidad,entidad_id,detalle)values(auth.uid(),'club_crea_revisar','club_creator_projects',v_id,jsonb_build_object('status',p_status,'has_note',v_note is not null));return jsonb_build_object('ok',true,'id',v_id,'status',p_status,'review_note',v_note);end;$$;

revoke all on function public.club_crea_listar(uuid,text) from public,anon,authenticated;revoke all on function public.club_crea_cargar(uuid,text,uuid) from public,anon,authenticated;revoke all on function public.club_crea_guardar(uuid,text,uuid,text,text,jsonb) from public,anon,authenticated;revoke all on function public.club_crea_archivar(uuid,text,uuid) from public,anon,authenticated;revoke all on function public.club_crea_solicitar_revision(uuid,text,uuid) from public,anon,authenticated;revoke all on function public.club_crea_versiones(uuid,text,uuid) from public,anon,authenticated;revoke all on function public.club_crea_restaurar(uuid,text,uuid,integer) from public,anon,authenticated;revoke all on function public.club_crea_plantillas(uuid,text) from public,anon,authenticated;revoke all on function public.club_crea_assets_listar(uuid,text) from public,anon,authenticated;revoke all on function public.club_crea_asset_guardar(uuid,text,uuid,uuid,text,text,jsonb) from public,anon,authenticated;revoke all on function public.club_crea_asset_borrar(uuid,text,uuid) from public,anon,authenticated;revoke all on function public.club_crea_revision() from public,anon,authenticated;revoke all on function public.club_crea_revisar(uuid,text,text) from public,anon,authenticated;
grant execute on function public.club_crea_listar(uuid,text) to anon,authenticated;grant execute on function public.club_crea_cargar(uuid,text,uuid) to anon,authenticated;grant execute on function public.club_crea_guardar(uuid,text,uuid,text,text,jsonb) to anon,authenticated;grant execute on function public.club_crea_archivar(uuid,text,uuid) to anon,authenticated;grant execute on function public.club_crea_solicitar_revision(uuid,text,uuid) to anon,authenticated;grant execute on function public.club_crea_versiones(uuid,text,uuid) to anon,authenticated;grant execute on function public.club_crea_restaurar(uuid,text,uuid,integer) to anon,authenticated;grant execute on function public.club_crea_plantillas(uuid,text) to anon,authenticated;grant execute on function public.club_crea_assets_listar(uuid,text) to anon,authenticated;grant execute on function public.club_crea_asset_guardar(uuid,text,uuid,uuid,text,text,jsonb) to anon,authenticated;grant execute on function public.club_crea_asset_borrar(uuid,text,uuid) to anon,authenticated;grant execute on function public.club_crea_revision() to authenticated;grant execute on function public.club_crea_revisar(uuid,text,text) to authenticated;
